In [9]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually


In [10]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Info:")
df.info()

Shape: (3900, 18)

Columns:
['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category', 'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status', 'Shipping Type', 'Discount Applied', 'Promo Code Used', 'Previous Purchases', 'Payment Method', 'Frequency of Purchases']

Data Types:
Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)       int64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Promo Code Used            object
Previous Purchases          int64
Payment Method             object
Frequency of Purchases     object
dtype: object

Dataset Info:
<class 'pandas.core.frame.Dat

In [11]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000


In [12]:
missing = df.isnull().sum()

missing[missing > 0]

Review Rating    37
dtype: int64

,Missing Values,Missing %
Review Rating,37,0.95


In [14]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0


In [15]:
for col in df.columns:
    print(f"\n{col}")
    print("Unique values:", df[col].nunique())
    print(df[col].unique()[:10])


Customer ID
Unique values: 3900
[ 1  2  3  4  5  6  7  8  9 10]

Age
Unique values: 53
[55 19 50 21 45 46 63 27 26 57]

Gender
Unique values: 2
['Male' 'Female']

Item Purchased
Unique values: 25
['Blouse' 'Sweater' 'Jeans' 'Sandals' 'Sneakers' 'Shirt' 'Shorts' 'Coat'
 'Handbag' 'Shoes']

Category
Unique values: 4
['Clothing' 'Footwear' 'Outerwear' 'Accessories']

Purchase Amount (USD)
Unique values: 81
[53 64 73 90 49 20 85 34 97 31]

Location
Unique values: 50
['Kentucky' 'Maine' 'Massachusetts' 'Rhode Island' 'Oregon' 'Wyoming'
 'Montana' 'Louisiana' 'West Virginia' 'Missouri']

Size
Unique values: 4
['L' 'S' 'M' 'XL']

Color
Unique values: 25
['Gray' 'Maroon' 'Turquoise' 'White' 'Charcoal' 'Silver' 'Pink' 'Purple'
 'Olive' 'Gold']

Season
Unique values: 4
['Winter' 'Spring' 'Summer' 'Fall']

Review Rating
Unique values: 26
[3.1 3.5 2.7 2.9 3.2 2.6 4.8 4.1 4.9 4.5]

Subscription Status
Unique values: 2
['Yes' 'No']

Shipping Type
Unique values: 6
['Express' 'Free Shipping' 'Next Da

In [16]:
num_cols = df.select_dtypes(include=np.number).columns

df[num_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,1950.500000,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,44.068462,15.207589,18.0,31.00,44.0,57.00,70.0
Purchase Amount (USD),3900.0,59.764359,23.685392,20.0,39.00,60.0,81.00,100.0
Review Rating,3863.0,3.750065,0.716983,2.5,3.10,3.8,4.40,5.0
Previous Purchases,3900.0,25.351538,14.447125,1.0,13.00,25.0,38.00,50.0


In [17]:
df["Purchase Amount (USD)"].describe()

count    3900.000000
mean       59.764359
std        23.685392
min        20.000000
25%        39.000000
50%        60.000000
75%        81.000000
max       100.000000
Name: Purchase Amount (USD), dtype: float64

In [18]:
df["Purchase Amount (USD)"].mean()

59.76435897435898

In [19]:
df.groupby("Category")["Purchase Amount (USD)"].agg(
    ["count", "sum", "mean"]
).sort_values("sum", ascending=False)

,count,sum,mean
Category,,,
Clothing,1737,104264,60.025331
Accessories,1240,74200,59.838710
Footwear,599,36093,60.255426
Outerwear,324,18524,57.172840


In [20]:
df.groupby("Gender")["Purchase Amount (USD)"].agg(
    ["count", "sum", "mean"]
)

,count,sum,mean
Gender,,,
Female,1248,75191,60.249199
Male,2652,157890,59.536199


In [21]:
df.groupby("Season")["Purchase Amount (USD)"].agg(
    ["count", "sum", "mean"]
).sort_values("sum", ascending=False)

,count,sum,mean
Season,,,
Fall,975,60018,61.556923
Spring,999,58679,58.737738
Winter,971,58607,60.357364
Summer,955,55777,58.405236


In [22]:
df["Item Purchased"].value_counts().head(10)

Item Purchased
Blouse        171
Jewelry       171
Pants         171
Shirt         169
Dress         166
Sweater       164
Jacket        163
Belt          161
Sunglasses    161
Coat          161
Name: count, dtype: int64

In [23]:
df.groupby("Previous Purchases")["Purchase Amount (USD)"].mean().head(20)

Previous Purchases
1     58.469880
2     60.333333
3     58.560440
4     61.274725
5     64.252874
6     55.850575
7     61.200000
8     66.671642
9     63.784615
10    58.184211
11    59.500000
12    59.253165
13    55.884058
14    57.967391
15    55.863014
16    62.157143
17    61.462687
18    59.142857
19    57.474359
20    61.891566
Name: Purchase Amount (USD), dtype: float64

In [24]:
df.groupby("Subscription Status")["Purchase Amount (USD)"].agg(
    ["count", "sum", "mean"]
)

,count,sum,mean
Subscription Status,,,
No,2847,170436,59.865121
Yes,1053,62645,59.491928


In [25]:
df.groupby("Discount Applied")["Purchase Amount (USD)"].agg(
    ["count", "sum", "mean"]
)

,count,sum,mean
Discount Applied,,,
No,2223,133670,60.130454
Yes,1677,99411,59.279070


In [26]:
df.groupby("Promo Code Used")["Purchase Amount (USD)"].agg(
    ["count", "sum", "mean"]
)

,count,sum,mean
Promo Code Used,,,
No,2223,133670,60.130454
Yes,1677,99411,59.279070


In [27]:
bins = [0, 18, 25, 35, 45, 55, 65, 100]

labels = [
    "Under 18",
    "18-25",
    "26-35",
    "36-45",
    "46-55",
    "56-65",
    "65+"
]

df["Age Group"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels
)

df["Age Group"].value_counts().sort_index()

Age Group
Under 18     69
18-25       502
26-35       742
36-45       729
46-55       753
56-65       750
65+         355
Name: count, dtype: int64

In [28]:
df.groupby("Age Group", observed=True)["Purchase Amount (USD)"].agg(
    ["count", "mean", "sum"]
)

,count,mean,sum
Age Group,,,
Under 18,69,59.985507,4139
18-25,502,60.739044,30491
26-35,742,59.760108,44342
36-45,729,59.305898,43234
46-55,753,60.583001,45619
56-65,750,59.136000,44352
65+,355,58.884507,20904


In [29]:
df[num_cols].corr()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
Customer ID,1.000000,-0.004079,0.011048,0.000247,-0.039159
Age,-0.004079,1.000000,-0.010424,-0.024384,0.040445
Purchase Amount (USD),0.011048,-0.010424,1.000000,0.029859,0.008063
Review Rating,0.000247,-0.024384,0.029859,1.000000,0.003583
Previous Purchases,-0.039159,0.040445,0.008063,0.003583,1.000000


In [30]:
df[num_cols].corr()["Purchase Amount (USD)"].sort_values(
    ascending=False
)

Purchase Amount (USD)    1.000000
Review Rating            0.029859
Customer ID              0.011048
Previous Purchases       0.008063
Age                     -0.010424
Name: Purchase Amount (USD), dtype: float64

In [31]:
Q1 = df["Purchase Amount (USD)"].quantile(0.25)
Q3 = df["Purchase Amount (USD)"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Purchase Amount (USD)"] < lower) |
    (df["Purchase Amount (USD)"] > upper)
]

print("Number of outliers:", len(outliers))

Number of outliers: 0


In [33]:
!pip install pyodbc sqlalchemy

In [34]:
import pandas as pd
from sqlalchemy import create_engine

# SQL Server connection
server = r"localhost\SQLEXPRESS01"
database = "CustomerShoppingDB"

engine = create_engine(
    "mssql+pyodbc://localhost\\SQLEXPRESS01/CustomerShoppingDB"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
)

print("Connected successfully!")

Connected successfully!


In [36]:
df = pd.read_csv("customer_shopping_behavior.csv")

df.to_sql(
    "CustomerShopping",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully!")

InterfaceError: (pyodbc.InterfaceError) ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'KANAN-SBEAST07\\kanan\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "CustomerShoppingDB" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'KANAN-SBEAST07\\kanan\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "CustomerShoppingDB" requested by the login. The login failed. (4060)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)

In [37]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mssql+pyodbc://localhost\\SQLEXPRESS01/CustomerShoppingDB"
    "?trusted_connection=yes"
    "&driver=ODBC+Driver+17+for+SQL+Server"
)

print("Connected successfully!")

Connected successfully!


In [38]:
df = pd.read_csv("customer_shopping_behavior.csv")

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually


In [39]:
df.to_sql(
    "CustomerShopping",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully!")

C:\Users\kanan\anaconda3\Lib\site-packages\pandas\io\sql.py:1636: SAWarning: Unrecognized server version info '17.0.1125.2'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())


Data loaded successfully!
